dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo apt-get install -y -qqlibgtest-dev cmake  
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
#  - sudo apt-get update -qq
#  - sudo apt-get install -y -qq graphviz libgtest-dev cmake
#  - git submodule add git@github.com:google/googletest.git
#  - sudo ./ci/travis.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

before_deploy: 
  - 'export _PROJECT_NAME="HW7L16-Cmd"'
  - 'export _PACKAGE_NAME="bulk"'
  - 'export _PROJECT_VERSION=`grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" cmake/GetGitRevisionDescription/version.cpp`'

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - '! curl -T ${_PACKAGE_NAME}-${_PROJECT_VERSION}-Linux.deb -uboydad:$BINTRAY_API_KEY "https://api.bintray.com/content/boydad/otus-cpp/${_PROJECT_NAME}/${_PROJECT_VERSION}/${_PROJECT_NAME}/${_PACKAGE_NAME}-${_PROJECT_VERSION}-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" | grep -v success'
